services:
  api:
    image: api
    container_name: api
    env_file: .env
    build:
      dockerfile: Dockerfile.debug
    networks:
      - todo
    ports:
      - 8080:8081
      - 4000:4000

  db:
    image: postgres:18-alpine
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - todo

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - todo

networks:
  todo:
